apiVersion: v1
kind: Service
metadata:
  labels:
    app: testapp
  name: testapp
spec:
  ports:
    - name: 8080-tcp
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    deploymentconfig: testapp
  sessionAffinity: None
  type: ClusterIP

